/**
 * Pre-built document templates — rich, evocative starting points for each
 * document category.  These are consumed by game.dc.register_gear_templates()
 * and the GM Documents tab template gallery.
 *
 * Each template is a complete gear item object (same shape as document_templates
 * in register.js).  The template gallery renders draggable cards from these.
 */

const DOCUMENT_TEMPLATES = {

  // ─── Newspaper ────────────────────────────────────────────────────────

  newspaper_template: {
    label: 'The Tombstone Epitaph',
    cost: 5,
    quantity: 1,
    weight: 0,
    category: 'newspaper',
    content_type: 'newspaper',
    url: '',
    text_content: '',
    image: '',
    newspaper_data: null,
    rarity: 'common',
    description: 'A periodical or broadsheet. Use the newspaper editor to create procedural layout content.',
    user_made: false,
  },

  // ─── Wanted Posters ───────────────────────────────────────────────────

  wanted_dead_or_alive: {
    label: 'WANTED: Dead or Alive',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'wanted_poster',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    wanted_poster_data: {
      name: '',
      alias: '',
      crime: '',
      details: 'Last seen heading west toward the territory line. Consider armed and dangerous.',
      description: '',
      reward: '$500',
      contact: "Local Sheriff's Office",
      portrait: '',
    },
    rarity: 'common',
    description: 'A blank wanted poster with the classic DEAD OR DEAD header. Fill in the outlaw\'s details.',
    user_made: false,
  },
  wanted_murder_suspect: {
    label: 'Wanted: Murder Suspect',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'wanted_poster',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    wanted_poster_data: {
      name: '',
      alias: '',
      crime: 'Murder',
      details: 'Wanted for the killing of a respected townsman outside the saloon on the night of October 3rd. Witnesses report a dispute over a card game.',
      description: 'Male, approximately 30 years of age, medium build. Last seen wearing a dust-colored duster and a slouch hat.',
      reward: '$1,000',
      contact: "U.S. Marshal's Office, Dodge City",
      portrait: '',
    },
    rarity: 'common',
    description: 'A pre-filled murder wanted poster with evocative crime details and physical description.',
    user_made: false,
  },
  wanted_cattle_rustler: {
    label: 'Wanted: Cattle Rustler',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'wanted_poster',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    wanted_poster_data: {
      name: '',
      alias: '"The Rail Splitter"',
      crime: 'Cattle Rustling',
      details: 'Suspected of driving off two dozen head of cattle from the Bar-X ranch in the past month. Works with a small gang of three to five men.',
      description: 'Male, lean build, wears a bandana over the lower face. Rides a bay gelding with a white blaze.',
      reward: '$250',
      contact: 'Bar-X Ranch, near Tombstone',
      portrait: '',
    },
    rarity: 'common',
    description: 'A cattle rustling poster with gang details and a catchy alias to get the creative juices flowing.',
    user_made: false,
  },
  wanted_train_robber: {
    label: 'Wanted: Train Robber',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'wanted_poster',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    wanted_poster_data: {
      name: '',
      alias: '',
      crime: 'Train Robbery',
      details: 'Held up the Southern Pacific express near Contention, relieving passengers of gold and valuables. Armed with a Winchester rifle and a Navy Colt.',
      description: 'Male, tall, dark-haired. Speaks with a Southern accent. May have been wounded in the exchange.',
      reward: '$2,500',
      contact: 'Southern Pacific Railroad, Tucson Division',
      portrait: '',
    },
    rarity: 'common',
    description: 'A dramatic train robbery poster with high reward and period-specific details.',
    user_made: false,
  },

  // ─── Letters ───────────────────────────────────────────────────────────

  letter_formal_business: {
    label: 'Formal Business Letter',
    cost: 100,
    quantity: 1,
    weight: 0,
    category: 'letter',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    letter_data: {
      date: '',
      sender: '',
      recipient: '',
      salutation: 'Dear Sir,',
      body: [
        'I write to you on behalf of my employer regarding the matter we discussed in our previous correspondence.',
        'The terms proposed are acceptable in principle, though we would request a small adjustment to the schedule of payments.',
        'We await your response at your earliest convenience.',
      ],
      closing: 'Yours faithfully,',
      signature: '',
      stationery: 'formal',
    },
    rarity: 'common',
    description: 'A formal business letter with proper salutation, structured body, and formal closing.',
    user_made: false,
  },
  letter_telegram: {
    label: 'Telegram',
    cost: 50,
    quantity: 1,
    weight: 0,
    category: 'letter',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    letter_data: {
      date: '',
      sender: 'WESTERN UNION',
      recipient: '',
      salutation: '',
      body: [
        'STOP',
        'URGENT MESSAGE STOP',
        'ARRIVING ON TOMORROWS NOON STAGE STOP',
        'HAVE THE MONEY READY STOP',
        'TELL NO ONE STOP',
      ],
      closing: 'END',
      signature: '',
      stationery: 'telegram',
    },
    rarity: 'common',
    description: 'A period telegram with STOP-separated lines and urgent tone. Great for plot hooks.',
    user_made: false,
  },
  letter_personal: {
    label: 'Personal Letter',
    cost: 100,
    quantity: 1,
    weight: 0,
    category: 'letter',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    letter_data: {
      date: '',
      sender: '',
      recipient: '',
      salutation: 'My dearest,',
      body: [
        'I hope this letter finds you well. The town is quiet tonight, and I find myself thinking of home more than usual.',
        'The work here is harder than I expected, but I am saving what I can and hope to return by the spring.',
        'Give my regards to the family. I think of you all every day.',
      ],
      closing: 'With all my love,',
      signature: '',
      stationery: 'handwritten',
    },
    rarity: 'common',
    description: 'A warm personal letter on handwritten stationery — perfect for NPC backstory or plot handouts.',
    user_made: false,
  },
  letter_threat: {
    label: 'Threat Letter',
    cost: 100,
    quantity: 1,
    weight: 0,
    category: 'letter',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    letter_data: {
      date: '',
      sender: 'A Friend',
      recipient: '',
      salutation: '',
      body: [
        'You have something that does not belong to you.',
        'We know where you sleep. We know where your children play.',
        'Leave town by sundown Friday or we will come for what is ours — and everything else besides.',
      ],
      closing: 'You have been warned.',
      signature: '',
      stationery: 'handwritten',
    },
    rarity: 'common',
    description: 'A menacing anonymous threat letter on handwritten stationery. Drops tension into any campaign.',
    user_made: false,
  },
  letter_love: {
    label: 'Love Letter',
    cost: 100,
    quantity: 1,
    weight: 0,
    category: 'letter',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    letter_data: {
      date: '',
      sender: '',
      recipient: '',
      salutation: 'My darling,',
      body: [
        'I cannot bear another day without writing to you. The miles between us feel like years.',
        'I dream of the morning I will see your face again. Until that day, I carry your smile with me like a coin I will not spend.',
        'Wait for me. I am coming home.',
      ],
      closing: 'Forever yours,',
      signature: '',
      stationery: 'handwritten',
    },
    rarity: 'common',
    description: 'A romantic love letter on handwritten stationery — great for character-driven story moments.',
    user_made: false,
  },

  // ─── Journals ─────────────────────────────────────────────────────────

  journal_trail: {
    label: 'Trail Journal',
    cost: 500,
    quantity: 1,
    weight: 1,
    category: 'journal',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    journal_data: {
      title: '',
      author: '',
      entries: [
        { date: 'March 14th', title: 'Setting Out', body: 'Left Tombstone at dawn with three days\' provisions. The trail north is dry but passable. Saw dust on the horizon to the east — riders, though I could not make out their number.' },
        { date: 'March 15th', title: 'The Dry Gulch', body: 'Waterhole at Dry Gulch had run to mud. Filled the canteens anyway. The horse is favoring her left fore — may need to rest her a day if it does not improve.' },
        { date: 'March 16th', title: 'Smoke Signals', body: 'Spotted smoke rises to the north in the early evening. Could be a signal fire or a camp. I will approach with caution come morning. Something does not feel right about this country.' },
      ],
    },
    rarity: 'uncommon',
    description: 'A rugged frontiersman\'s trail journal with three evocative entries — perfect for exploration campaigns.',
    user_made: false,
  },
  journal_doctors_notes: {
    label: "Doctor's Notes",
    cost: 500,
    quantity: 1,
    weight: 1,
    category: 'journal',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    journal_data: {
      title: '',
      author: '',
      entries: [
        { date: 'Oct 2', title: 'Case: Gunshot Wound', body: 'Male, mid-30s. Entry wound left shoulder, ball lodged against the scapula. Extracted without complication. Patient responsive. Prescribed laudanum for pain and iodine dressing.' },
        { date: 'Oct 4', title: 'Case: Fever', body: 'Female, early 20s. Persistent fever, delirium. No visible wounds. Suspect malaria — administer quinine. Monitor.' },
        { date: 'Oct 7', title: 'Follow-Up', body: 'Gunshot patient recovering well, fever reduced. The fever case is worsening despite treatment. Considering the possibility of something beyond natural illness.' },
      ],
    },
    rarity: 'uncommon',
    description: 'A frontier doctor\'s clinical notes with three cases — hints of something supernatural in the final entry.',
    user_made: false,
  },
  journal_lawmans_log: {
    label: "Lawman's Log",
    cost: 500,
    quantity: 1,
    weight: 1,
    category: 'journal',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    journal_data: {
      title: '',
      author: '',
      entries: [
        { date: 'Monday', title: 'Disturbance at the saloon', body: 'Broke up a fight between two drifters and a local ranch hand around 9 pm. No serious injuries. Ran the drifters out of town with a warning. One of them — tall man, scar on his cheek — gave me a look I did not care for.' },
        { date: 'Tuesday', title: 'Report of theft', body: 'Mrs. Henderson reports a gold locket stolen from her dresser sometime in the night. No sign of forced entry. Suspicious — she boarded a new hired hand last week.' },
        { date: 'Wednesday', title: 'The tall man returns', body: 'The drifter from Monday was seen back in town today. He was asking after the stage schedule at the general store. Keeping an eye on him.' },
      ],
    },
    rarity: 'uncommon',
    description: 'A frontier lawman\'s duty log with three days of escalating incidents — ready-made plot seeds.',
    user_made: false,
  },
  journal_missionary: {
    label: "Missionary's Diary",
    cost: 500,
    quantity: 1,
    weight: 1,
    category: 'journal',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    journal_data: {
      title: '',
      author: '',
      entries: [
        { date: 'June 1st', title: 'Arrival', body: 'Reached the mission after three weeks of hard travel. The land is beautiful but wild. The Apache have been peaceful so far, and I pray it remains so. The chapel needs a new roof before the rains.' },
        { date: 'June 14th', title: 'First Service', body: 'Held my first proper service today. Eight souls attended, including a family from the mining camp. The faith is weak here but it is not dead. I will tend it.' },
        { date: 'July 3rd', title: 'Strange Tales', body: 'The miners speak of something in the hills that is not of this world. I dismissed it as drink and superstition, but I confess I heard something in the wind last night that did not sound like any animal I know.' },
      ],
    },
    rarity: 'uncommon',
    description: "A missionary's diary with faith, hope, and creeping dread — ideal for Weird West adventures.",
    user_made: false,
  },

  // ─── Ledgers ───────────────────────────────────────────────────────────

  ledger_general_store: {
    label: 'General Store Ledger',
    cost: 200,
    quantity: 1,
    weight: 1,
    category: 'ledger',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    ledger_data: {
      account_name: 'General Store — Daily Transactions',
      period: 'October 1881',
      currency_label: '$',
      rows: [
        { date: 'Oct 1', description: 'Flour, 50 lbs (J. Smith)', debit: '', credit: '3.50', balance: '' },
        { date: 'Oct 1', description: 'Coffee, 2 lbs (J. Smith)', debit: '', credit: '1.00', balance: '' },
        { date: 'Oct 2', description: 'Inventory restock — ammunition', debit: '25.00', credit: '', balance: '' },
        { date: 'Oct 3', description: 'Rope, 30 ft (Ranch foreman)', debit: '', credit: '2.50', balance: '' },
        { date: 'Oct 4', description: 'Lamp oil, 1 gal (Mrs. Parker)', debit: '', credit: '0.75', balance: '' },
      ],
    },
    rarity: 'common',
    description: 'A general store daily transaction ledger with realistic entries — perfect for shop-keeping NPCs.',
    user_made: false,
  },
  ledger_cattle_ranch: {
    label: 'Cattle Ranch Ledger',
    cost: 200,
    quantity: 1,
    weight: 1,
    category: 'ledger',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    ledger_data: {
      account_name: 'Bar-X Ranch — Cattle Sales',
      period: 'Spring 1881',
      currency_label: '$',
      rows: [
        { date: 'Apr 15', description: 'Sold 40 head to railhead, $22/head', debit: '', credit: '880.00', balance: '' },
        { date: 'Apr 20', description: 'Branding supplies (iron, paint)', debit: '15.00', credit: '', balance: '' },
        { date: 'May 2', description: 'Hay, 10 tons for winter', debit: '120.00', credit: '', balance: '' },
        { date: 'May 10', description: 'Sold 25 head to Army contract', debit: '', credit: '650.00', balance: '' },
        { date: 'May 28', description: 'Veterinary services — 3 head', debit: '18.00', credit: '', balance: '' },
      ],
    },
    rarity: 'common',
    description: 'A cattle ranch sales ledger with realistic livestock transaction entries.',
    user_made: false,
  },
  ledger_bank: {
    label: 'Bank Account Ledger',
    cost: 200,
    quantity: 1,
    weight: 1,
    category: 'ledger',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    ledger_data: {
      account_name: 'First Territorial Bank — Account of W. Earp',
      period: 'August 1881',
      currency_label: '$',
      rows: [
        { date: 'Aug 1', description: 'Opening balance', debit: '', credit: '', balance: '' },
        { date: 'Aug 3', description: 'Deposit — salary', debit: '', credit: '75.00', balance: '' },
        { date: 'Aug 7', description: 'Withdrawal — ammunition', debit: '12.00', credit: '', balance: '' },
        { date: 'Aug 14', description: 'Withdrawal — lodging', debit: '20.00', credit: '', balance: '' },
        { date: 'Aug 20', description: 'Deposit — bounty payment', debit: '', credit: '250.00', balance: '' },
      ],
    },
    rarity: 'uncommon',
    description: 'A bank account ledger with deposits, withdrawals, and a bounty payment — story clues in the numbers.',
    user_made: false,
  },
  ledger_saloon_tab: {
    label: 'Saloon Tab Ledger',
    cost: 200,
    quantity: 1,
    weight: 1,
    category: 'ledger',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    ledger_data: {
      account_name: 'The Crystal Palace — Customer Tabs',
      period: 'September 1881',
      currency_label: '$',
      rows: [
        { date: 'Sep 1', description: 'Whiskey, 3 rounds (Doc H.)', debit: '', credit: '1.50', balance: '' },
        { date: 'Sep 1', description: 'Beer, 2 rounds (card players)', debit: '', credit: '0.40', balance: '' },
        { date: 'Sep 3', description: 'Room, 1 night (stranger)', debit: '', credit: '0.50', balance: '' },
        { date: 'Sep 5', description: 'Tab paid — Doc H.', debit: '1.50', credit: '', balance: '' },
        { date: 'Sep 8', description: 'Whiskey, bottle (private room)', debit: '', credit: '2.00', balance: '' },
      ],
    },
    rarity: 'common',
    description: 'A saloon customer tab ledger with whiskey, beer, rooms, and tabs paid — character clues abound.',
    user_made: false,
  },

  // ─── Maps ──────────────────────────────────────────────────────────────

  map_trail: {
    label: 'Trail Map',
    cost: 1000,
    quantity: 1,
    weight: 0,
    category: 'map',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    map_data: {
      image: '',
      title: 'Trail to Contention',
      scale_label: '1 inch = 5 miles',
      markers: [
        { x_pct: 15, y_pct: 80, label: 'Tombstone (start)', icon: 'fa-flag' },
        { x_pct: 40, y_pct: 55, label: 'Waterhole', icon: 'fa-tint' },
        { x_pct: 65, y_pct: 40, label: 'Dry Gulch', icon: 'fa-mountain' },
        { x_pct: 85, y_pct: 20, label: 'Contention', icon: 'fa-flag-checkered' },
      ],
    },
    rarity: 'uncommon',
    description: 'A trail map with waypoints — waterholes, landmarks, and destination. Just add an image.',
    user_made: false,
  },
  map_territory: {
    label: 'Territory Map',
    cost: 1000,
    quantity: 1,
    weight: 0,
    category: 'map',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    map_data: {
      image: '',
      title: 'Arizona Territory',
      scale_label: '1 inch = 20 miles',
      markers: [
        { x_pct: 25, y_pct: 70, label: 'Tombstone', icon: 'fa-home' },
        { x_pct: 45, y_pct: 50, label: 'Tucson', icon: 'fa-home' },
        { x_pct: 60, y_pct: 30, label: 'Prescott', icon: 'fa-home' },
        { x_pct: 80, y_pct: 60, label: 'Fort Huachuca', icon: 'fa-shield' },
      ],
    },
    rarity: 'uncommon',
    description: 'A territory map with major towns and a military fort. Good for strategic overviews.',
    user_made: false,
  },
  map_mine: {
    label: 'Mine Map',
    cost: 1000,
    quantity: 1,
    weight: 0,
    category: 'map',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    map_data: {
      image: '',
      title: 'Silver Lance Mine',
      scale_label: '1 inch = 100 feet',
      markers: [
        { x_pct: 50, y_pct: 10, label: 'Main Entrance', icon: 'fa-door-open' },
        { x_pct: 30, y_pct: 45, label: 'Shaft A', icon: 'fa-hammer' },
        { x_pct: 65, y_pct: 50, label: 'Shaft B (collapsed)', icon: 'fa-triangle-exclamation' },
        { x_pct: 50, y_pct: 80, label: 'Deep Level', icon: 'fa-arrow-down' },
      ],
    },
    rarity: 'uncommon',
    description: 'A mine layout map with shafts, entrances, and a hazard marker. Perfect for underground adventures.',
    user_made: false,
  },
  map_town: {
    label: 'Town Plat',
    cost: 1000,
    quantity: 1,
    weight: 0,
    category: 'map',
    content_type: 'image',
    url: '',
    text_content: '',
    image: '',
    map_data: {
      image: '',
      title: 'Town of Dusty Creek',
      scale_label: '1 inch = 50 feet',
      markers: [
        { x_pct: 20, y_pct: 30, label: "Sheriff's Office", icon: 'fa-star' },
        { x_pct: 50, y_pct: 35, label: 'Saloon', icon: 'fa-beer-mug-empty' },
        { x_pct: 35, y_pct: 60, label: 'General Store', icon: 'fa-store' },
        { x_pct: 70, y_pct: 55, label: "Doctor's Office", icon: 'fa-staff-snake' },
        { x_pct: 80, y_pct: 25, label: 'Livery Stable', icon: 'fa-horse' },
        { x_pct: 15, y_pct: 70, label: 'Train Depot', icon: 'fa-train' },
      ],
    },
    rarity: 'uncommon',
    description: 'A town plat map with labelled buildings — sheriff, saloon, store, doctor, stable, depot.',
    user_made: false,
  },

  // ─── Other Documents ──────────────────────────────────────────────────

  other_wanted_notice: {
    label: 'Wanted Notice',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'other',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    other_data: {
      title: 'NOTICE',
      body: 'By order of the Territorial Governor, a reward of $500 is hereby offered for information leading to the capture of the individual or individuals responsible for the robbery of the Butterfield Stage on the 14th instant.\n\nAny person found harbouring or aiding said individuals shall be considered an accessory and prosecuted to the fullest extent of the law.\n\nInquiries to the Sheriff\'s Office.',
      style: 'notice',
    },
    rarity: 'common',
    description: 'A formal public notice offering a reward. Great for posting on town bulletin boards.',
    user_made: false,
  },
  other_proclamation: {
    label: 'Town Proclamation',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'other',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    other_data: {
      title: 'PROCLAMATION',
      body: 'Hear ye, hear ye! By the authority vested in this office, let it be known that the carrying of firearms within the town limits is hereby prohibited between the hours of sundown and sunrise.\n\nAny person found in violation of this ordinance shall be subject to a fine of $10 or no less than one night in the county jail.\n\nGiven under my hand this day, the Mayor.',
      style: 'proclamation',
    },
    rarity: 'common',
    description: 'A dramatic proclamation with old-west legal language — perfect for establishing town rules.',
    user_made: false,
  },
  other_obituary: {
    label: 'Obituary',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'other',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    other_data: {
      title: 'In Memoriam',
      body: 'It is with heavy heart that we record the passing of , a longtime resident of this town and a friend to all who knew him.\n\nBorn in the East, he came west seeking fortune and found instead a community that loved him. He was a man of quiet courage, quick to lend a hand and slow to speak ill of any soul.\n\nHe is survived by his wife and two children. Services will be held at the chapel on Sunday next. In lieu of flowers, the family requests donations to the school fund.\n\nRequiescat in pace.',
      style: 'plain',
    },
    rarity: 'common',
    description: 'A heartfelt obituary with period language — can be customized for any NPC death.',
    user_made: false,
  },
  other_reward_poster: {
    label: 'Reward Poster',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'other',
    content_type: 'text',
    url: '',
    text_content: '',
    image: '',
    other_data: {
      title: 'REWARD',
      body: '$200 REWARD\n\nFor the return of a bay gelding, white blaze, branded on the left hip with a diamond and the letters DX.\n\nLast seen tied outside the saloon on Friday last. The horse answers to the name "Judge."\n\nNo questions asked. Contact the livery stable.\n\n$200 REWARD',
      style: 'notice',
    },
    rarity: 'common',
    description: 'A reward poster for a lost horse with branded details and a no-questions-asked return.',
    user_made: false,
  },

  // ─── Books ───────────────────────────────────────────────────────────

  book_template: {
    label: 'Book',
    cost: 0,
    quantity: 1,
    weight: 2,
    category: 'book',
    content_type: 'ia_book',
    url: '',
    text_content: '',
    image: '',
    book_data: {
      url: '',
      title: '',
      author: '',
      default_page: '',
      notes: 'Add an archive.org details page URL to embed the book reader.',
    },
    rarity: 'rare',
    description: 'A generic book template. Add an archive.org URL to embed the full book via the Internet Archive reader.',
    user_made: false,
  },

  // ─── Web Pages ─────────────────────────────────────────────────────────

  web_page_wiki: {
    label: 'Deadlands Wiki',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'web_page',
    content_type: 'url',
    url: '',
    text_content: '',
    image: '',
    web_page_data: {
      url: '',
      title: 'Deadlands Wiki',
      notes: 'Fan-maintained Deadlands reference wiki. Set the URL to embed the page.',
    },
    rarity: 'common',
    description: 'Template for a Deadlands wiki reference page. Add a URL to embed.',
    user_made: false,
  },
  web_page_peg: {
    label: 'Pinnacle Entertainment Group',
    cost: 0,
    quantity: 1,
    weight: 0,
    category: 'web_page',
    content_type: 'url',
    url: '',
    text_content: '',
    image: '',
    web_page_data: {
      url: '',
      title: 'Pinnacle Entertainment Group',
      notes: 'Official publisher site for Deadlands. Add a URL to embed.',
    },
    rarity: 'common',
    description: 'Template for the official Pinnacle Entertainment Group website. Add a URL to embed.',
    user_made: false,
  },
};

// Category metadata for the template gallery UI.
// Maps each category to an icon and display order.
const TEMPLATE_CATEGORY_META = {
  wanted_poster: { icon: 'fa-scroll', order: 1 },
  letter: { icon: 'fa-envelope', order: 2 },
  journal: { icon: 'fa-book-open', order: 3 },
  ledger: { icon: 'fa-table', order: 4 },
  map: { icon: 'fa-map', order: 5 },
  newspaper: { icon: 'fa-newspaper', order: 6 },
  book: { icon: 'fa-book', order: 7 },
  web_page: { icon: 'fa-globe', order: 8 },
  other: { icon: 'fa-file-lines', order: 9 },
};

/**
 * Get templates grouped by category, sorted by category order.
 * @returns {Array<{category: string, icon: string, label: string, templates: Array}>}
 */
function get_template_groups() {
  const by_category = {};
  for (const [key, tmpl] of Object.entries(DOCUMENT_TEMPLATES)) {
    const cat = tmpl.category;
    if (!by_category[cat]) by_category[cat] = [];
    by_category[cat].push({ key, ...tmpl });
  }

  return Object.entries(by_category)
    .map(([category, templates]) => {
      const meta = TEMPLATE_CATEGORY_META[category] || { icon: 'fa-file', order: 99 };
      return {
        category,
        icon: meta.icon,
        label: game.i18n.localize(`dc.containers.doc.categories.${category}`),
        order: meta.order,
        templates,
      };
    })
    .sort((a, b) => a.order - b.order);
}

export {
  DOCUMENT_TEMPLATES,
  TEMPLATE_CATEGORY_META,
  get_template_groups,
};